---
- hosts: localhost
  tasks:
    - name: Validate PostgreSQL configuration
      ansible.builtin.assert:
        that:
          - postgresql is defined
          - postgresql.database is defined
          - postgresql.username is defined
          - postgresql.password is defined
          - postgresql.host is defined
          - postgresql.port is defined
          - interfaces is defined
          - interfaces|length > 0
        fail_msg: "All PostgreSQL configuration variables must be defined"

    - name: Ensure directories are created
      loop:
        - "{{ rootfs }}"
        - "{{ rootfs }}/etc"
        - "{{ rootfs }}/etc/kea"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory

    - name: Generate entrypoint.sh
      ansible.builtin.template:
        src: entrypoint.sh.j2
        dest: "{{ rootfs }}/entrypoint.sh"

    - name: Generate kea-dhcp4.conf
      ansible.builtin.template:
        src: kea-dhcp4.conf.j2
        dest: "{{ rootfs }}/etc/kea/kea-dhcp4.conf"
