---
- name: Converge
  hosts: all
  gather_facts: false
  roles:
    - jasonn3.frr
  tasks:
    - name: Display frr.conf contents
      command: cat frr.router1.conf chdir={{ rootfs }}/etc/frr
      register: command_output
      changed_when: false

    - name: Print to console
      debug:
        msg: "{{command_output.stdout}}"

    - name: Check bgp
      when: ('bgp' in routers.router1.router)
      command: /usr/lib/frr/bgpd -C -f {{ rootfs }}/etc/frr/frr.router1.conf -n -Z -S
      changed_when: false

    - name: Check ospf
      when: ('ospf' in routers.router1.router)
      command: /usr/lib/frr/ospfd -C -f {{ rootfs }}/etc/frr/frr.router1.conf -n -Z -S
      changed_when: false
