---
driver:
  name: podman
platforms:
  - name: instance
    image: quay.io/frrouting/frr:10.2.3
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: group_vars
verifier:
  name: ansible
