---
rootfs: /
routers:
  router1:
    id: 10.0.1.1
    interfaces:
      - name: lo
        ip: 10.0.1.1/32

      - name: eth0
        ip: 10.0.0.1/24
        ospf:
          authentication:
            message_digest:
              keys:
                - OSPFPASSWORD
          bfd: true
        mpls: true

      - name: eth1
        ospf:
          passive: true
        vrrp:
          id: 1
          priority: 100
          ip: 10.0.2.1

      - name: eth2
        ospf:
          passive: true
        vrrp:
          id: 2
          priority: 100
          ip: 10.0.3.1
    router:
      bgp:
        - asn: 64496
          connect_timer: 5
          neighbors:
            groups:
              - name: group1
                cidr: 10.0.4.0/24
                asn: 64497
            routers:
              - address: 10.0.1.2
                asn: 64496
                bfd: true
                update_source: lo
                password: BGPPASSWORD
              - address: 10.0.1.3
                asn: 64496
                bfd: true
                update_source: lo
                password: BGPPASSWORD
          redistribute:
            - connected
          summaries:
            - 10.0.4.0/23
            - 10.0.5.0/24
      ospf:
        - redistribute:
            - connected
          networks:
            - 10.0.0.0/24
            - 10.0.1.1/24
            - 10.0.2.0/24
            - 10.0.3.0/24
    mpls:
      interfaces:
        - eth0