---
- hosts: localhost
  tasks:
    - name: Ensure directories are created
      loop:
        - "{{ rootfs }}"
        - "{{ rootfs }}/etc"
        - "{{ rootfs }}/etc/openvpn"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'

    - name: Generate {{ item.src | splitext | first }}
      loop:
        - src: entrypoint.sh.j2
          dst: entrypoint.sh
        - src: server.conf.j2
          dst: etc/openvpn/server.conf
        - src: openvpn-auth-oauth2.yaml
          dst: etc/openvpn/openvpn-auth-oauth2.yaml
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ rootfs }}/{{ item.dst }}"
        mode: "{{ item.mode | default('0644') }}"

    - name: Write CA Certificate
      when: ca is defined
      ansible.builtin.copy:
        content: "{{ ca }}"
        dest: "{{ rootfs }}/etc/openvpn/ca.pem"

    - name: Generate random mgmt password
      ansible.builtin.copy:
        content: "{{ lookup('community.general.random_string', length=64) }}"
        dest: "{{ rootfs }}/etc/openvpn/mgmt.txt"
