FROM docker.io/library/alpine:3.22.0

RUN apk add --no-cache \
      bash kea-dhcp4 kea-hook-pgsql-cb kea-hook-ha

COPY rootfs /

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/usr/sbin/kea-dhcp4", "-c", "/etc/kea/kea-dhcp4.conf"]