FROM docker.io/library/alpine:3.22.0

RUN apk add --no-cache \
      bash \
      jq \
      kea-dhcp4 kea-hook-pgsql-cb kea-hook-ha \
      socat \
      tini

COPY rootfs /

RUN /usr/sbin/kea-dhcp4 -t /etc/kea/kea-dhcp4.conf

HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
  CMD /healthcheck.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/usr/sbin/kea-dhcp4", "-c", "/etc/kea/kea-dhcp4.conf"]
