FROM docker.io/library/alpine:3.22.0

RUN apk update && \
    apk add --no-cache \
      kea-dhcp4 kea-hook-mysql-cb kea-hook-ha

COPY rootfs /

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/usr/sbin/kea-dhcp4", "-c", "/etc/kea/kea-dhcp4.conf"]