name: Build Container

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      ref:
        type: string
        required: true

jobs:
  load_vars:
    name: Load Variables
    uses: ./.github/workflows/vars.yaml

  build-container:
    needs:
      - load_vars
    strategy:
      fail-fast: false
      matrix:
        app: ${{ fromJson(needs.load_vars.outputs.APPS) }}
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        include:
          - os: ubuntu-24.04
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64
    name: Build Container Image
    runs-on: ${{ matrix.os }}
    environment: dev
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref}}
          submodules: recursive
          fetch-depth: 0
          fetch-tags: 'true'

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          context: ${{ inputs.ref != '' && 'git' || 'workflow' }}
          flavor: |
            suffix=-${{ matrix.app }}-${{ matrix.arch }}
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}

      - name: Buildah Build
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: ${{ matrix.app }}/Containerfile
          context: ${{ matrix.app }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Write keyfile
        run: |
          set -euxo pipefail
          keyfile="$(mktemp)"
          echo "${{ secrets.JWE_KEY }}" > "${keyfile}"
          echo "keyfile=${keyfile}" >> "$GITHUB_ENV"

      - name: Encrypt final layer and push image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          extra-args: |
            --encrypt-layer -1
            --encryption-key jwe:${{ env.keyfile }}

      - name: Delete keyfile
        run: |
          set -euxo pipefail
          rm -f "${{ env.keyfile }}"

  combine-tags:
    strategy:
      fail-fast: false
      matrix:
        app:
          - chrony
    name: Combine Tags
    runs-on: ubuntu-24.04
    needs: build-container
    permissions:
      packages: write
    steps:
      - name: Checkout
        if: ${{ inputs.ref != '' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref}}
          submodules: recursive
          fetch-depth: 0
          fetch-tags: 'true'

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          context: ${{ inputs.ref != '' && 'git' || 'workflow' }}
          flavor: |
            suffix=-${{ matrix.app }}
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}

      - name: Generate manifest
        run: |
          for tag in $(echo "${{ steps.meta.outputs.tags }}" | tr '\n' ' ')
          do
            podman manifest create ${tag}
            podman manifest add ${tag} \
              docker://${tag}-amd64 \
              --arch amd64
            podman manifest add ${tag} \
              docker://${tag}-arm64 \
              --arch arm64
          done
      - name: Push manifest
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ghcr.io/${{ github.repository }}
          tags: ${{ steps.meta.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
