name: Build Container

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

  #schedule:
    # Patch Tuesday (Second Tuesday of the month)
  #  - cron: "0 7 8-14 * 2"

jobs:
  build-container:
    strategy:
      fail-fast: false
      matrix:
        app:
          - chrony
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        include:
          - os: ubuntu-24.04
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64
    name: Build Container Image
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          fetch-tags: 'true'

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            suffix=-${{ matrix.app }}-${{ matrix.arch }}
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}

      - name: Buildah Build
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: ${{ matrix.app }}/Containerfile
          context: ${{ matrix.app }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Write keyfile
        run: |
          set -euxo pipefail
          keyfile=$(mktemp)
          echo "${{ secrets.JWE_KEY }}" > ${keyfile}
          echo "keyfile=${keyfile}" >> $GITHUB_ENV

      - name: Encrypt final layer and push image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          extra-args: |
            --encrypt-layer -1
            --encryption-key jwe:${{ env.keyfile }}

      - name: Delete keyfile
        run: |
          set -euxo pipefail
          rm -f ${keyfile}

          

  combine-tags:
    strategy:
      fail-fast: false
      matrix:
        app:
          - chrony
    name: Combine Tags
    runs-on: ubuntu-24.04
    needs: build-container
    permissions:
      packages: write
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            suffix=-${{ matrix.app }}
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}

      - name: Generate manifest
        run: |
          for tag in ${{ steps.meta.outputs.tags }}
          do
            podman manifest create ${tag}
            podman manifest add ${tag} \
              docker://${tag}-amd64 \
              --arch amd64
            podman manifest add ${tag} \
              docker://${tag}-arm64 \
              --arch arm64
          done
      - name: Push manifest
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ghcr.io/${{ github.repository }}
          tags: ${{ steps.meta.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
