on:
  push:
    branches:
      - main
      - dev

jobs:
  load_vars:
    name: Load Variables
    uses: ./.github/workflows/vars.yaml

  next_step:
    name: Get next step
    runs-on: ubuntu-latest
    needs:
      - load_vars
    outputs:
      step: ${{ steps.get_next.outputs.step }}
    steps:
      - name: Get next step
        id: get_next
        run: |
          next_step=$(echo '${{ needs.load_vars.outputs.LIFECYCLE }}' | jq -r '.[ index("${{ github.ref_name }}") + 1 ]')
          echo "step=${next_step}" >> "$GITHUB_OUTPUT"

  create_pr:
    name: Create PR
    runs-on: ubuntu-latest
    needs:
      - load_vars
      - next_step
    steps:
      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          next_month=$(date -d "next month" '+%Y-%m (%B %Y)')
          gh pr create --base ${{ needs.next_step.outputs.step }} --head ${{ github.ref_name }} --label lifecycle --title "Monthly Updates - ${next_month} - ${{ needs.next_step.outputs.step }}" --body "Changes to ${{ github.ref_name }} to apply to ${{ needs.next_step.outputs.step }} during the next patch cycle"