name: Promote to prod

on:
  schedule:
    # Patch Tuesday + 1 week (Third Tuesday of the month)
    - cron: "0 7 15-21 * 2"

jobs:
  promote-to-dev:
    uses: ./.github/workflows/step_lifecycle.yml
    with:
      next_step: "prod"