name: Load Variables

on:
  workflow_call:
    outputs:
      APPS:
        value: '[
          "chrony",
          "conntrackd",
          "frr",
          "haproxy",
          "kea",
          "nut",
          "wireguard"
          ]'

jobs:
  load-vars:
    name: Load Variable
    runs-on: ubuntu-latest
    steps:
      - name: Sucess
        run: echo "Vars loaded"
